services:
  myPostgresDb:
    image: postgres
    restart: always
    ports:
      - "5455:5432"
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: BenBouiss 
      POSTGRES_DB: D4G
